// From https://github.com/firebase/firebaseui-web/blob/master/LANGUAGES.md

export const languagesWithTranslations = {
  'ar': 'ar',
  'bg': 'bg',
  'ca': 'ca',
  'zh_cn': 'zh_cn',
  'zh_tw': 'zh_tw',
  'hr': 'hr',
  'cs': 'cs',
  'da': 'da',
  'nl': 'nl',
  'en': 'en',
  'en_gb': 'en_gb',
  'fa': 'fa',
  'fil': 'fil',
  'fi': 'fi',
  'fr': 'fr',
  'de': 'de',
  'el': 'el',
  'iw': 'iw', // Hebrew (not 'he')
  'hi': 'hi',
  'hu': 'hu',
  'id': 'id',
  'it': 'it',
  'ja': 'ja',
  'ko': 'ko',
  'lv': 'lv',
  'lt': 'lt',
  'no': 'no',
  'pl': 'pl',
  'pt_br': 'pt_br',
  'pt_pt': 'pt_pt',
  'ro': 'ro',
  'ru': 'ru',
  'sr': 'sr',
  'sk': 'sk',
  'sl': 'sl',
  'es': 'es',
  'es_41': 'es_41',
  'sv': 'sv',
  'th': 'th',
  'tr': 'tr',
  'uk': 'uk',
  'vi': 'vi',
} as const;

export type LanguageCode = keyof typeof languagesWithTranslations;
