<script>import { MainPage } from "kitbook";
export let data;
</script>

<MainPage {data} />

<!-- Kitbook route files were auto-generated by kitbook@1.0.0-beta.17^ - Do not edit as they will be overwritten next time kitbook updates routing. -->
